// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDio9eAzVnCG87We_mUiGbr8jaFcl7tIVk',
    appId: '1:529160572463:web:5e4c54c67e074255d600da',
    messagingSenderId: '529160572463',
    projectId: 'greenify-e29c7',
    authDomain: 'greenify-e29c7.firebaseapp.com',
    storageBucket: 'greenify-e29c7.firebasestorage.app',
    measurementId: 'G-FJXSTK55H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqvL0JjP9YESnB6NEXM0SvLP_sY9uudQ',
    appId: '1:529160572463:android:c0e7cf948f863648d600da',
    messagingSenderId: '529160572463',
    projectId: 'greenify-e29c7',
    storageBucket: 'greenify-e29c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecG4rY4ffHbWSnO_43tPKUc-Dy5dYE2Y',
    appId: '1:529160572463:ios:fa2e3693411c1fd0d600da',
    messagingSenderId: '529160572463',
    projectId: 'greenify-e29c7',
    storageBucket: 'greenify-e29c7.firebasestorage.app',
    iosBundleId: 'com.example.greenify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecG4rY4ffHbWSnO_43tPKUc-Dy5dYE2Y',
    appId: '1:529160572463:ios:fa2e3693411c1fd0d600da',
    messagingSenderId: '529160572463',
    projectId: 'greenify-e29c7',
    storageBucket: 'greenify-e29c7.firebasestorage.app',
    iosBundleId: 'com.example.greenify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDio9eAzVnCG87We_mUiGbr8jaFcl7tIVk',
    appId: '1:529160572463:web:b606d6abaa214c5ed600da',
    messagingSenderId: '529160572463',
    projectId: 'greenify-e29c7',
    authDomain: 'greenify-e29c7.firebaseapp.com',
    storageBucket: 'greenify-e29c7.firebasestorage.app',
    measurementId: 'G-JXW06EYG37',
  );
}
